-- Add slug column to products
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;

-- Generate slug for existing products
UPDATE public.products SET slug = LOWER(REGEXP_REPLACE(name, '[^a-zA-Z0-9]+', '-', 'g')) WHERE slug IS NULL;

-- If there are duplicates generated by the simple slugification, you might need to handle them manually,
-- but the above usually handles simple cases.

-- Now, in your code, you will fetch by slug instead of id.
